version: 2.1
branches:
  only:
    - master
orbs:
  node: circleci/node@5.0.2
  eb: circleci/aws-elastic-beanstalk@2.0.1
  aws-cli: circleci/aws-cli@3.1.1
jobs:
  build:
    docker:
      - image: "cimg/node:20.16"
    steps:
      - node/install
      - checkout
      - aws-cli/setup
      - eb/setup
      - run:
          name: Configure AWS Config
          command: |
            aws configure set region $AWS_DEFAULT_REGION
            aws configure set output json
      - run:
          name: Configure AWS Credentials
          command: |
            aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
            aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
      - run:
          name: Set environment variables in EB
          command: |
            cd mystore-be
            eb init mystore-be --region $AWS_DEFAULT_REGION --platform "64bit Amazon Linux 2 v5.9.4 running Node.js 18"
            eb use mystore-be-dev
            eb setenv AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION
      - run:
          name: Front-End Install
          command: |
            npm run frontend:install
      - run:
          name: Back-End Install
          command: |
            npm run backend:install
      - run:
          name: Front-End Build
          command: |
            npm run frontend:build
      - run:
          name: Back-End Build
          command: |
            npm run backend:build
      - run:
          name: Deploy BE
          command: |
            npm run backend:deploy
      - run:
          name: Deploy FE
          command: |
            npm run frontend:deploy
